#+TITLE: Breves anotações a três acórdãos recentes em matéria de divórcio transnacional
#+AUTHOR: João Gomes de Almeida
#+cite_export: csl chicago.csl

* Introdução

No dia 13 de dezembro de 2021 tive o prazer e a honra de colaborar com o Centro de Estudos Judiciários na ação de formação contínua sobre o Direito Internacional da Família. No âmbito desta colaboração abordei o tema /"O Divórcio e a Regulação do Exercício das Responsabilidades Parentais em Contexto Transfronteiriço"/.

No contexto deste /ebook/ do Centro de Estudos Judiciários pareceu-me interessante complementar a comunicação proferida com breves anotações a três acórdãos recentes (e, a meu ver, bastante relevantes) em matéria de divórcio transnacional. O primeiro é o Acórdão do Tribunal de Justiça da União da Europeia (TJ) de 25 de novembro de 2021, /IB contra FA/, C-289/20, [[https://curia.europa.eu/juris/liste.jsf?oqp=&for=&mat=or&jge=&td=%3BALL&jur=C%2CT%2CF&num=C-289%252F20&page=1&dates=&pcs=Oor&lg=&pro=&nat=or&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&language=pt&avg=&cid=663452][EU:C:2021:955]]. Atendendo à data em que foi proferido, foi-me ainda possível fazer uma brevíssima menção a este Acórdão na ação de formação, que agora tenho o ensejo de desenvolver. O segundo é o Acórdão da /Cour de cassation/ francesa, de 26 de janeiro de 2022, Pourvoi n° 20-21.542, [[https://www.courdecassation.fr/decision/61f0f2367743e3330ccf0756?judilibre_chambre%5B%5D=civ1&search_api_fulltext=&expression_exacte=&date_du=2022-01-26&date_au=2022-01-26&sort=&items_per_page=&op=Filtrer&page=4&previousdecisionpage=4&previousdecisionindex=6&nextdecisionpage=4&nextdecisionindex=8][ECLI:FR:CCASS:2022:C100078]]. Este recentíssimo Acórdão suscita uma interessante questão quanto ao exercício da autonomia privada na determinação da lei reguladora do divórcio. O terceiro é o Acórdão do TJ de 10 de fevereiro de 2022, /OE contra VY/, C-522/20, [[https://curia.europa.eu/juris/liste.jsf?oqp=&for=&mat=or&jge=&td=%3BALL&jur=C%2CT%2CF&num=C-522%252F20&page=1&dates=&pcs=Oor&lg=&pro=&nat=or&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&language=pt&avg=&cid=776477][EU:C:2022:87]], em que se analisa a relevância da nacionalidade à luz do princípio da não discriminação em razão da nacionalidade.

Espero que as breves anotações que se seguem sejam um complemento e contributo interessante para todos quantos estudam estas problemáticas.

* O Acórdão do Tribunal de Justiça da União da Europeia de 25 de novembro de 2021, /IB contra FA/, proc. C-289/20, [[https://curia.europa.eu/juris/liste.jsf?oqp=&for=&mat=or&jge=&td=%3BALL&jur=C%2CT%2CF&num=C-289%252F20&page=1&dates=&pcs=Oor&lg=&pro=&nat=or&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&language=pt&avg=&cid=663452][EU:C:2021:955]][fn:1]

** Os factos do caso

IB, nacional francês, casou com FA, nacional irlandesa, em 1994[fn:2]. Fixaram domicílio conjugal na Irlanda, em 1999[fn:3]. IB alegou, no processo judicial de divórcio por si intentado, que exerce desde 2010 a sua atividade profissional em França e de forma estável e permanente desde maio de 2017. Mais alegou que se instalou num imóvel pertencente ao seu pai, tem uma vida social em França e foi a recusa de FA em residir em França, apesar permanecer regularmente no citado imóvel e na casa de férias adquirida em 2017, que os levou a ter vidas separadas[fn:4].

O órgão jurisdicional de reenvio considerou que IB tinha duas residências: uma familiar, na Irlanda, e uma profissional, na França. No processo judicial de divórcio existem numerosos elementos que caracterizam a ligação pessoal e familiar de IB à Irlanda, para onde se deslocava todos os fins de semana a fim de se juntar à mulher e aos filhos, mas também uma ligação profissional a França, para onde se deslocava todas as semanas, para trabalhar[fn:5].

** A questão prejudicial

Atendendo aos dois vínculos de residência de IB, o órgão jurisdicional de reenvio decidiu colocar a seguinte questão prejudicial:

#+begin_quote
«Quando […] resulte das circunstâncias de facto que um dos cônjuges divide a sua vida entre dois Estados-Membros, pode considerar-se, na aceção do artigo 3.º do Regulamento n.º 2201/2003 e para efeitos da sua aplicação, que esse cônjuge tem a sua residência habitual em dois Estados-Membros, de modo que, se os requisitos estabelecidos nesse artigo estiverem preenchidos relativamente a dois Estados-Membros, os tribunais desses dois Estados são igualmente competentes para decidir sobre o divórcio?»[fn:6]
#+end_quote

** A resposta do Tribunal de Justiça da União Europeia

O TJ começa por sintetizar a questão colocada pelo órgão jurisdicional de reenvio: um cônjuge que divide a sua vida entre dois Estados-Membros pode ter a sua residência habitual nesses dois Estados-Membros, de modo que os tribunais destes últimos podem ser competentes para decidir do pedido de dissolução do vínculo matrimonial?[fn:7]

Assinala, depois, que o conceito de residência habitual /não/ é definido no Regulamento Bruxelas II /bis/[fn:8], devendo ser interpretado autonomamente, tendo em conta o contexto das disposições que o mencionam e os objetivos do referido regulamento[fn:9].

Observando as disposições do Regulamento Bruxelas II /bis/, verifica que nenhuma emprega o conceito na forma plural, destacando, no âmbito das questões suscitadas por ordenamentos jurídicos complexos, que a referência à residência habitual diz respeito à residência habitual numa unidade territorial[fn:10].

Releva, depois, a sua jurisprudência sobre o conceito de residência habitual (do menor), na qual se acentua a residência habitual como centro permanente onde se situam os interesses da pessoa. O elemento histórico depõe no sentido de o conceito ter sido adotado no Regulamento Bruxelas II /bis/ atendendo à interpretação do TJ, pois tal é assinalado no Relatório Explicativo da Convenção de Bruxelas II, que esteve na génese do Regulamento Bruxelas II /bis/[fn:12]. Conclui que a ideia de centro de interesses não aponta no sentido de o conceito residência habitual poder suscitar problemas de conteúdo múltiplo, isto é, de permitir que, em simultâneo, uma pessoa tenha mais do que uma residência habitual[fn:11].

Esta conclusão é, no entender do TJ, corroborada pelos objetivos prosseguidos com as normas atribuitivas de competência internacional em matéria de divórcio, separação judicial e anulação do casamento previstas no artigo 3.º, n.º 1, alínea /a)/, que consiste em assegurar um equilíbrio entre a mobilidade das pessoas no interior da União Europeia e a segurança jurídica[fn:13]. O TJ considera que admitir a possibilidade de um cônjuge ter mais de uma residência habitual em simultâneo acarretaria o risco de a a competência internacional determinada, em última análise, não pelo critério da «residência habitual», mas por um critério baseado na simples residência de um ou de outro dos cônjuges, o que infringiria o Regulamento Bruxelas II /bis/[fn:14]. O risco à previsibilidade jurídica seria acrescido por outros regulamentos atribuírem competências noutras matérias, como obrigações alimentares ou regimes matrimoniais, ao tribunal internacionalmente competente para julgar a ação de divórcio, separação judicial ou anulação do casamento[fn:15].

Considerou que a sua anterior jurisprudência em matéria de plurinacionalidade comum dos cônjuges (Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, [[http://curia.europa.eu/juris/liste.jsf?language=pt&jur=C,T,F&num=C-168/08&td=ALL][EU:C:2009:474]]) não aponta em sentido contrário, pois a conclusão de que o conceito de nacionalidade consagrado no Regulamento Bruxelas II /bis/ não se encontra limitado à /nacionalidade efetiva/ não é relevante para a interpretação do conceito de residência habitual consagrado no artigo 3.º, n.º 1, alínea /a)/, do Regulamento Bruxelas II /bis/[fn:16].

Conclui, com estes fundamentos, que embora não esteja excluído que um cônjuge possa dispor simultaneamente de várias residências, apenas pode ter, num determinado momento, uma única residência habitual, na aceção do artigo 3.º, n.º 1, alínea /a)/, do Regulamento Bruxelas II /bis/[fn:17].

De seguida, o TJ efetua algumas considerações sobre o conceito autónomo de residência habitual. Seguindo a sua anterior jurisprudência, assinala que o conceito reflete essencialmente uma questão de facto, devendo os tribunais atender a todas as circunstâncias de facto específicas do caso concreto[fn:18]. Após recordar a sua anterior jurisprudência em matéria de residência habitual de crianças, conclui que as circunstâncias específicas que permitem determinar a residência habitual de crianças não são idênticas em todos os aspectos às que permitem determinar a residência habitual dos cônjuges[fn:19]. Assim, um cônjuge pode, nomeadamente em casos de crise conjugal, abandonar a antiga residência habitual e fixar nova residência habitual noutro Estado-Membro e, ainda assim, manter alguns vínculos sociais e familiares no Estado-Membro da anterior residência habitual[fn:20]. Ao contrário das crianças, em especial as de tenra idade, o ambiente em que se encontra integrado um adulto é de natureza mais variada, sendo constituído por um espetro de atividades sensivelmente mais vasto e de interesses, designadamente profissionais, socioculturais, patrimoniais e de ordem privada e familiar, diversificados e, por isso, conclui o TJ que não é possível exigir que todos esses interesses se concentrem num único Estado-Membro[fn:21].

O TJ recorda, por fim, que a interpretação do conceito autónomo de residência habitual se caracteriza, em princípio, por dois elementos, a saber, por um lado, a vontade do interessado de fixar o centro habitual dos seus interesses num determinado lugar, e, por outro, uma presença com um grau suficiente de estabilidade no território do Estado-Membro em causa[fn:24]. A esta luz, e para que seja possível recorrer aos critérios de competência previstos no artigo 3.º, n.º 1, al. /a)/, quinto e sexto travessões, do Regulamento Bruxelas II /bis/, o cônjuge requerente deve ter transferido a sua residência habitual para o território de um Estado-Membro diferente do da anterior residência habitual comum e, portanto, por um lado, ter manifestado a vontade de estabelecer o centro habitual dos seus interesses nesse outro Estado-Membro, e, por outro, ter demonstrado que a sua presença no território deste Estado-Membro revela um grau suficiente de estabilidade[fn:22]. No caso concreto, o TJ entendeu indicar que os elementos constantes dos autos parecem, /a priori/, permitir demontrar a transferência de residência, o carácter estável da mesma e, pelo menos, a integração do cônjuge requerente no ambiente social e cultural do Estado-Membro da nova residência[fn:23]; não deixou, porém, de assinalar que compete ao órgão jurisdicional de reenvio a concreta tarefa de verificar se houve ou não, no caso concreto, mudança da residência habitual do cônjuge requerente[fn:25].

** Análise
** Conclusões

* O Acórdão da /Cour de cassation/ francesa, de 26 de janeiro de 2022, Pourvoi n° 20-21.542, [[https://www.courdecassation.fr/decision/61f0f2367743e3330ccf0756?judilibre_chambre%5B%5D=civ1&search_api_fulltext=&expression_exacte=&date_du=2022-01-26&date_au=2022-01-26&sort=&items_per_page=&op=Filtrer&page=4&previousdecisionpage=4&previousdecisionindex=6&nextdecisionpage=4&nextdecisionindex=8][ECLI:FR:CCASS:2022:C100078]]

** Os factos do caso
** A questão relevante
** A resposta da /Cour de cassation/
** Análise
** Conclusões

* O o Acórdão do TJ de 10 de fevereiro de 2022, /OE contra VY/, C-522/20, [[https://curia.europa.eu/juris/liste.jsf?oqp=&for=&mat=or&jge=&td=%3BALL&jur=C%2CT%2CF&num=C-522%252F20&page=1&dates=&pcs=Oor&lg=&pro=&nat=or&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&language=pt&avg=&cid=776477][EU:C:2022:87]]
** Os factos do caso
** A questão prejudicial
** A resposta do Tribunal de Justiça da União Europeia
** Análise
** Conclusões

Aqui digo uma coisa muito interessante[cite: Cf., por exemplo, @almeida2017 p. 322 e ess.].

E isto também é interessante[cite: Ver, neste sentido,; @pinheiro2019b p. 12; @almeida2017 p. 54.].

* Footnotes
[fn:25] Considerando n.º 61.

[fn:24] Considerando n.º 57.

[fn:23] Considerandos n.º 59 e 60

[fn:22] Considerando n.º 58.

[fn:21] Considerando nº. 56.

[fn:20] Considerando n.º 55.

[fn:19] Considerandos n.ºs 53 e 54.

[fn:18] Considerando n.º 52.

[fn:17] Considerando n.º 51.

[fn:16] Considerandos n.º 49 e 50.

[fn:15] Considerando n.º 48.

[fn:14] Considerando n.º 46.

[fn:13] Considerando n.º 44.

[fn:12] Considerando n.º 42.

[fn:11] Considerandos n.º 41 e 43.

[fn:10] Considerando n.º 40.

[fn:9] Considerando n.º 39.

[fn:8] Considerando n.º 38.

[fn:7] Considerando n.º 30.

[fn:6] Considerando n.º 23.

[fn:5] Considerandos n.ºs 18 e 19.

[fn:4] Considerando n.º 16.

[fn:3] Considerando n.º 18.

[fn:2] Considerando n.º 13.

[fn:1] Os considerandos sem indicação de fonte pertencem ao Acórdão que se comenta.
